### ISSUE TITLE
polars dataframe needs write_parquet not to_parquet

### ISSUE THREAD

**Issue by windiana42** [pydiverse/pydiverse.pipedag#100]
PolarsParquetTableHook.materialize function includes `table.obj.table.obj.to_parquet(path)`. This should be `table.obj.table.obj.write_parquet(path)`

**Comment by windiana42** [comment]
https://github.com/pydiverse/pydiverse.pipedag/commit/f6492e34ec478c1ffd3a0dd04d0b6a57a12a952c#diff-efbdf1197b2c0218f2e0a35a8441695d8b7cf7ff994c1834ffe21b5f6448ceea

**Comment by NMAC427** [comment]
Fixed by 6d45c0d60be8be16a15bb3d5d143244f9f2a80c0
