### ISSUE TITLE
fix prefect 2 engine

### ISSUE THREAD

**Issue by windiana42** [pydiverse/pydiverse.pipedag#101]
Somehow `result.data` does not exist any more. This seems to work:
https://github.com/pydiverse/pydiverse.pipedag/commit/f6492e34ec478c1ffd3a0dd04d0b6a57a12a952c#diff-940ca4762598d885160f9c92fdf15448e797974b5e3ed58099194466e6cfdca0

**Comment by NMAC427** [comment]
Fixed by 70e48803550a3995ec5fb345b5f558bbf5e0ed43
