### ISSUE TITLE
version 0.6.2 writes pandas tables with lowercase names to DB2

### ISSUE THREAD

**Issue by windiana42** [pydiverse/pydiverse.pipedag#106]
Even if writing table "_FILTER_IDS" as an output of a task with `dag.Table(df, "_FILTER_IDS")`, the table is written with lowercase name to DB2 even quoted as can be seen in ALTER TABLE statement adding indexes `<schema>."_filter_ids"`.

DB2 has by default uppercase name. So the opposite should actually happen.

**Comment by NMAC427** [comment]
Pipedag tables names are case insensitive: https://github.com/pydiverse/pydiverse.pipedag/blob/43f0e3bab7e6b16d6f2023d2c87cf1f8c1f34c9a/src/pydiverse/pipedag/util/naming.py#L6-L13

**Comment by NMAC427** [comment]
However, this needs to be documenter better.
