### ISSUE TITLE
Making `ignore_fresh_input` more explicit (or the docs)

### ISSUE THREAD

**Issue by MarcAntoineSchmidtQC** [pydiverse/pydiverse.pipedag#107]
I might misunderstand the docs, but this seems to indicate that when this parameter is True, we want to ignore the cache and always update the table.

> ignore_fresh_input – When set to True, the task’s cache function gets ignored when determining the cache validity of a task.

However, the name "ignore fresh input" suggests that we do not want to refresh the tables, even when the inputs have changed.

Could you clarify which one it is?

**Comment by NMAC427** [comment]
Setting `ignore_fresh_input` to True results in the behaviour described by the documentation. However, I agree that it is an unfortunate name. I think I will rename it to `ignore_cache_function` to make it clearer.
