### ISSUE TITLE
for DB2 database: allow configuring table creation properties globally and/or per schema or table

### ISSUE THREAD

**Issue by windiana42** [pydiverse/pydiverse.pipedag#113]
In DB2 there are many options in table creation which can result in significant speeds. 

- [ ] Explicit table spaces can be chosen
- [ ] A separate table space for indexes is often used
- [ ] Compression can be activated `COMPRESS YES ADAPTIVE ACTIVATE VALUE COMPRESSION`

**Comment by nicolasmueller** [comment]
Compression is implemented in #122
