### ISSUE TITLE
Support for Postgres unlogged tables when copying tables

### ISSUE THREAD

**Issue by nicolasmueller** [pydiverse/pydiverse.pipedag#127]
Currently `CopyTable` does not yet support Postgres unlogged tables. Support should be added for unlogged tables to be created consistently when the `unlogged` `materialization_detail` is set.

**Comment by windiana42** [comment]
@nicolasmueller is this issue testable by combining this unlogged test with a cache invalidation test that partially invalidates some tables in a stage? https://gist.github.com/windiana42/aae986b9d0b2c1a4fdde43eab6fc2c49#file-test_postgres-py-L14
