### ISSUE TITLE
Make max_length = 5000 configurable in mssql dialect for RawSQL Strings

### ISSUE THREAD

**Issue by QuantCo-mr-T** [pydiverse/pydiverse.pipedag#146]
It is extremely valuable that the complete RawSQL string is printed after filling all programmatically chosen placeholders.
Thus the following setting in pydiverse/pipedag/backend/table/sql/dialects/mssql.py should be made configurable: 
```python
            max_length = 5000
```

**Comment by DominikZuercherQC** [comment]
See #155
