### ISSUE TITLE
Ipython / jupyter runs of pipedag (i.e. Interactive Window in VS Code)

### ISSUE THREAD

**Issue by windiana42** [pydiverse/pydiverse.pipedag#38]
I had trouble running pipedag in interactive window of VS Code. It said `No such option: --ip`. This error does not come on program start time. So I suspect it is caused in multiprocess fork moment of pipedag RunContextServer process (wild guess):
![image](https://user-images.githubusercontent.com/61181806/214145552-5ae7f461-36c3-4c08-84d4-72ad43a89442.png)

**Comment by NMAC427** [comment]
I wasn't able to reproduce this error. Do you have any more information regarding this issue?
