### ISSUE TITLE
Move config module outside of util / generally optimize public interface of pipedag

### ISSUE THREAD

**Issue by windiana42** [pydiverse/pydiverse.pipedag#43]
PipedagConfig and ConfigContext are two classes that users of pipedag want to interact with. I would say it looks weird to import things from util package. In the face of API stability, it might make sense to do this move rather early while adoption is still low.

**Comment by windiana42** [comment]
We might go as far as to import most public interface classes (i.e. Flow, Stage, PipedagConfig, ...) into toplevel package pydiverse.pipedag. This might give us more flexibility in how to restructure module hierarchies without breaking user code compatibility.

**Comment by windiana42** [comment]
In general it would make sense to look at all classes/modules imported by users of pipedag and to present a stable external API which is not prone to changes due to internal refactoring. Internal modules might be renamed with leading underscore.

**Comment by windiana42** [comment]
The following imports have been seen "in the wild":

import pydiverse.pipedag as dag
from pydiverse.pipedag import materialize
from pydiverse.pipedag.context import ConfigContext
from pydiverse.pipedag import Flow, Stage
from pydiverse.pipedag.util.config import PipedagConfig

Potentially irrelevant:
from pydiverse.pipedag.materialize.util import compute_cache_key

 

 

 

from pydiverse.pipedag.util import setup_structlog

from pydiverse.pipedag.util.config import PipedagConfig

 

 

 

from pydiverse.pipedag import materialize

 

from pydiverse.pipedag.context import ConfigContext

**Comment by NMAC427** [comment]
Adressed by #82
