### ISSUE TITLE
Reduce dialect specific name mangling code duplication 

### ISSUE THREAD

**Issue by windiana42** [pydiverse/pydiverse.pipedag#45]
Postgres uses lowercase identifiers as case insensitive. Thus we define this as default for pipedag. But IBM DB2 uses uppercase identifiers as case insensitive default. Thus we might need to uppercase all-lowercase identifiers before quoting them. This causes a lot of code duplication in sql_ddl.py since it was done in pragmatic fasion. The right way to do this might be creating a dialect specific name adaption mechanism for schemas and table/view/etc. identifiers. We might even extend this to a dialect specific object referencing mechanism which would extend for mssql to [{database}].[{schema}].[{table}] where we keep {database}.{schema} in what we (and SQL Alchemy) calls schema.

**Comment by windiana42** [comment]
sqlalchemy has a concept we might use: reflection.denormalize_name()

**Comment by NMAC427** [comment]
Fixed by a9703cd110c16d9f0eda066f307d78541c694d8f, cc943dd807943fe39c9b69be38d4a7928ff6262c, and 89439fa5560a9b474af14f0a6ddfe6547a82aae2
