### ISSUE TITLE
Support pandas 2.0 + polars with apache arrow backed dataframes

### ISSUE THREAD

**Issue by windiana42** [pydiverse/pydiverse.pipedag#56]
Both pandas 2.0 and polars are capable to work with apache arrow dataframes in the background. We may route pulling of data from DB via apache arrow and define type mappings accordingly.

**Comment by windiana42** [comment]
polars and pandas are supported but by default won't dematerialize from SQL via arrow dataframe

**Comment by NMAC427** [comment]
As of 5d2566573baf95392558ae4ffa39bf5e709ad0f3, pipedag supports pyarrow backed data frames.
