### ISSUE TITLE
Integration tests with various pandas and sqlalchemy versions

### ISSUE THREAD

**Issue by windiana42** [pydiverse/pydiverse.pipedag#64]
pipedag is developed using poetry. However, in projects, we mostly use conda. So it would be nice to build a conda package as part of the CI and to test it with a little test bench that runs for a combination of multiple pandas and sqlalchemy versions.

**Comment by NMAC427** [comment]
Fixed by 444e1e26fbf81780c4da04cde4344cee22d77f0d
