### ISSUE TITLE
publish documentation per release version

### ISSUE THREAD

**Issue by windiana42** [pydiverse/pydiverse.pipedag#78]
We already have config.rst documentation in the repo. For every released version, we would like to have a url for retrieving such documentation. 

Potentially look at pypackage-cookiecutter for automation ideas.

**Comment by windiana42** [comment]
=> ask Pavel, Ignacio, ...

**Comment by NMAC427** [comment]
Fixed by 4928d05c5bb3d10f58a7c7be8d9ee8a25b0111dd
