### ISSUE TITLE
sqlalchemy does not have a type called Double

### ISSUE THREAD

**Issue by QuantCo-mr-T** [pydiverse/pydiverse.pipedag#96]
see dtype.py:196:
            DType.FLOAT64: sa.Double(),

Is this a problem that ruff should have picked up?

**Comment by windiana42** [comment]
I have seen FLOAT(53)=double vs. FLOAT(24)=real/float but I am not sure this is reliable across all database targets. We can test with databases pipedag supports.
 
Random link about this topic: https://stackoverflow.com/questions/1056323/difference-between-numeric-float-and-decimal-in-sql-server
